/**
 * Preset shape types for DrawingML shapes.
 *
 * Reference: ST_ShapeType in ooxml-schemas/ISO-IEC29500-4_2016/dml-main.xsd
 *
 * @module
 */

/* cspell:disable */
/**
 * The name of a preset shape, exactly as it appears in OOXML (`a:prstGeom/@prst`).
 *
 * Covers all 187 values of `ST_ShapeType`, from basic shapes such as `"rect"`, `"ellipse"` and `"triangle"`
 * to lines and connectors, block arrows, stars, callouts and flowchart symbols.
 *
 * @publicApi
 */
export type PresetShapeType =
    | "line"
    | "lineInv"
    | "triangle"
    | "rtTriangle"
    | "rect"
    | "diamond"
    | "parallelogram"
    | "trapezoid"
    | "nonIsoscelesTrapezoid"
    | "pentagon"
    | "hexagon"
    | "heptagon"
    | "octagon"
    | "decagon"
    | "dodecagon"
    | "star4"
    | "star5"
    | "star6"
    | "star7"
    | "star8"
    | "star10"
    | "star12"
    | "star16"
    | "star24"
    | "star32"
    | "roundRect"
    | "round1Rect"
    | "round2SameRect"
    | "round2DiagRect"
    | "snipRoundRect"
    | "snip1Rect"
    | "snip2SameRect"
    | "snip2DiagRect"
    | "plaque"
    | "ellipse"
    | "teardrop"
    | "homePlate"
    | "chevron"
    | "pieWedge"
    | "pie"
    | "blockArc"
    | "donut"
    | "noSmoking"
    | "rightArrow"
    | "leftArrow"
    | "upArrow"
    | "downArrow"
    | "stripedRightArrow"
    | "notchedRightArrow"
    | "bentUpArrow"
    | "leftRightArrow"
    | "upDownArrow"
    | "leftUpArrow"
    | "leftRightUpArrow"
    | "quadArrow"
    | "leftArrowCallout"
    | "rightArrowCallout"
    | "upArrowCallout"
    | "downArrowCallout"
    | "leftRightArrowCallout"
    | "upDownArrowCallout"
    | "quadArrowCallout"
    | "bentArrow"
    | "uturnArrow"
    | "circularArrow"
    | "leftCircularArrow"
    | "leftRightCircularArrow"
    | "curvedRightArrow"
    | "curvedLeftArrow"
    | "curvedUpArrow"
    | "curvedDownArrow"
    | "swooshArrow"
    | "cube"
    | "can"
    | "lightningBolt"
    | "heart"
    | "sun"
    | "moon"
    | "smileyFace"
    | "irregularSeal1"
    | "irregularSeal2"
    | "foldedCorner"
    | "bevel"
    | "frame"
    | "halfFrame"
    | "corner"
    | "diagStripe"
    | "chord"
    | "arc"
    | "leftBracket"
    | "rightBracket"
    | "leftBrace"
    | "rightBrace"
    | "bracketPair"
    | "bracePair"
    | "straightConnector1"
    | "bentConnector2"
    | "bentConnector3"
    | "bentConnector4"
    | "bentConnector5"
    | "curvedConnector2"
    | "curvedConnector3"
    | "curvedConnector4"
    | "curvedConnector5"
    | "callout1"
    | "callout2"
    | "callout3"
    | "accentCallout1"
    | "accentCallout2"
    | "accentCallout3"
    | "borderCallout1"
    | "borderCallout2"
    | "borderCallout3"
    | "accentBorderCallout1"
    | "accentBorderCallout2"
    | "accentBorderCallout3"
    | "wedgeRectCallout"
    | "wedgeRoundRectCallout"
    | "wedgeEllipseCallout"
    | "cloudCallout"
    | "cloud"
    | "ribbon"
    | "ribbon2"
    | "ellipseRibbon"
    | "ellipseRibbon2"
    | "leftRightRibbon"
    | "verticalScroll"
    | "horizontalScroll"
    | "wave"
    | "doubleWave"
    | "plus"
    | "flowChartProcess"
    | "flowChartDecision"
    | "flowChartInputOutput"
    | "flowChartPredefinedProcess"
    | "flowChartInternalStorage"
    | "flowChartDocument"
    | "flowChartMultidocument"
    | "flowChartTerminator"
    | "flowChartPreparation"
    | "flowChartManualInput"
    | "flowChartManualOperation"
    | "flowChartConnector"
    | "flowChartPunchedCard"
    | "flowChartPunchedTape"
    | "flowChartSummingJunction"
    | "flowChartOr"
    | "flowChartCollate"
    | "flowChartSort"
    | "flowChartExtract"
    | "flowChartMerge"
    | "flowChartOfflineStorage"
    | "flowChartOnlineStorage"
    | "flowChartMagneticTape"
    | "flowChartMagneticDisk"
    | "flowChartMagneticDrum"
    | "flowChartDisplay"
    | "flowChartDelay"
    | "flowChartAlternateProcess"
    | "flowChartOffpageConnector"
    | "actionButtonBlank"
    | "actionButtonHome"
    | "actionButtonHelp"
    | "actionButtonInformation"
    | "actionButtonForwardNext"
    | "actionButtonBackPrevious"
    | "actionButtonEnd"
    | "actionButtonBeginning"
    | "actionButtonReturn"
    | "actionButtonDocument"
    | "actionButtonSound"
    | "actionButtonMovie"
    | "gear6"
    | "gear9"
    | "funnel"
    | "mathPlus"
    | "mathMinus"
    | "mathMultiply"
    | "mathDivide"
    | "mathEqual"
    | "mathNotEqual"
    | "cornerTabs"
    | "squareTabs"
    | "plaqueTabs"
    | "chartX"
    | "chartStar"
    | "chartPlus";
/* cspell:enable */

const CONNECTOR_SHAPE_TYPES: ReadonlySet<PresetShapeType> = new Set<PresetShapeType>([
    "line",
    "lineInv",
    "straightConnector1",
    "bentConnector2",
    "bentConnector3",
    "bentConnector4",
    "bentConnector5",
    "curvedConnector2",
    "curvedConnector3",
    "curvedConnector4",
    "curvedConnector5",
]);

/**
 * Whether a preset is a line or connector. Word writes these with `wps:cNvCnPr`
 * (connector properties) instead of `wps:cNvSpPr`.
 */
export const isConnectorShapeType = (type: PresetShapeType): boolean => CONNECTOR_SHAPE_TYPES.has(type);
