/**
 * How wide Word draws Arabic's letters in each of the forms it joins them in, the lam-alef ligatures and the tatweel, in
 * the fonts of the width tables whose Arabic Word lays out with its glyphs' own widths, plain and bold, and the font it
 * draws them in.
 *
 * Generated by scripts/generate-arabic-widths.ts from Word's PDF of scripts/layout-probes/stops2/word-stops-arabic.ts,
 * saved from Word 16 for Mac. Do not edit by hand.
 *
 * @module
 */
// cspell:ignore tatweel

/**
 * The letters the widths are for, in their order: Arabic's (U+0621 to U+063A and U+0641 to U+064A), and Persian's peh,
 * tcheh, jeh, keheh, gaf and farsi yeh
 */
export const ARABIC_LETTERS: string = "ءآأؤإئابةتثجحخدذرزسشصضطظعغفقكلمنهوىيپچژکگی";

/** The alefs lam joins with into a ligature, in the order of their widths */
export const LAM_ALEFS: string = "آأإا";

/**
 * How wide Word draws Arabic in a font, plain and bold, in tenths of a thousandth of an em, three digits each, of the 64
 * of `0-9a-zA-Z+/`, with "*" and two digits repeating what is before it that many more times: each letter of
 * {@link ARABIC_LETTERS} in its isolated, final, initial and medial forms, "!" for those a letter doesn't have; the
 * isolated and final ligature of lam with each of {@link LAM_ALEFS}; and the tatweel. And the font Word draws them in, when
 * it isn't the font's own.
 */
export type ArabicWidths = {
    readonly name: string;
    readonly drawnIn?: string;
    readonly regular: string;
    readonly bold: string;
};

export const ARABIC_WIDTHS: readonly ArabicWidths[] = [
    {
        name: "Arial",
        regular:
            "10u!*020wm0zT!!0wm0zT!!13x13x!!0wm0zT!!1zK1rY0C90C90wm0zT!!1Lu1Lu0C90C90I60WC!!1Lu1Lu0C90C91Lu1Lu0C90C91n+1ib1iO1iO1n+1ib1iO1iO1n+1ib1iO1iO0QK0QK!!0QK0QK!!1co1co!!1co1co!!20l20l1iY1iX20l20l1iY1iX2HB2HB24e24e2HC2HB24e24e1qT*071l016m1ib0ZA1l016m1ib0ZA1Xe1Xe0FQ0F31qT1qT0FQ0F31tX1tX0ZA0ZA1f81f70wm0wm0QP0QP0ZA0ZA1ib1ib0C90C90I60WC16m0ZA13x13x!!1zK1rY0C90C91zK1rY0C90C91Lu1Lu0C90C91n+1ib1iO1iO1co1co!!1+U2hK0ZA1gq1+U2hK0ZA1gq1zK1rY0C90C91l01tS1l01tS1l01tS1l01tS0wm",
        bold: "19g!*020Bf0DC!!0xU0AE!!16w16v!!0xU0AD!!1AJ1qb0Gr0Gq0xU0AD!!1Bu1Bu0Gr0Gq0RA10S!!1Bu1Bu0Gr0Gq1Bu1Bu0Gr0Gq1qc1ni1hO1hO1qc1ni1hO1hO1qc1ni1hO1hO0RA0Rz!!0RA0Rz!!13C13C!!13C13C!!2cy2cy1v41v32cy2cy1v41v32C12C11Uz1Uy2C12C11Uz1Uy1hO*071ky19f1ky0Uj1ky19f1ky0Uj1Sq1Sq0LD0OG1vH1vH0LD0OG1ky1ky0Uj0Uj16w16v0AD0AD0Uk0Uj10S10S1ky1ky0Gr0Gq0RA10S19f16v16w16v!!1AJ1mC0Gr0Gq1AJ1qb0Gr0Gq1Bu1Bu0Gr0Gq1qc1ni1hO1hO13C13C!!1Sg29l0Uj1kH1Sg29l0Uj1kH1AJ1mC0Gr0Gq1ky1t51b/1ky1b/1ky1b/1ky0u/",
    },
    {
        name: "Times New Roman",
        regular:
            "10u!*020wm0zT!!0wm0zT!!13x13x!!0wm0zT!!1zK1rY0C90C90wm0zT!!1Lu1Lu0C90C90I60WC!!1Lu1Lu0C90C91Lu1Lu0C90C91n+1ib1iO1iO1n+1ib1iO1iO1n+1ib1iO1iO0QK0QK!!0QK0QK!!1co1co!!1co1co!!20l20l1iY1iX20l20l1iY1iX2HB2HB24e24e2HC2HB24e24e1qT*071l016m1ib0ZA1l016m1ib0ZA1Xe1Xe0FQ0F31qT1qT0FQ0F31tX1tX0ZA0ZA1f81f70wm0wm0QP0QP0ZA0ZA1ib1ib0C90C90I60WC16m0ZA13x13x!!1zK1rY0C90C91zK1rY0C90C91Lu1Lu0C90C91n+1ib1iO1iO1co1co!!1+U2hK0ZA1gq1+U2hK0ZA1gq1zK1rY0C90C91l01tS1k/1tS1l01tS1l01tS0wm",
        bold: "19g!*020Bf0DC!!0xU0AE!!16w16v!!0xU0AD!!1AJ1qb0Gr0Gq0xU0AD!!1Bu1Bu0Gr0Gq0RA10S!!1Bu1Bu0Gr0Gq1Bu1Bu0Gr0Gq1qc1ni1hO1hO1qc1ni1hO1hO1qc1ni1hO1hO0RA0Rz!!0RA0Rz!!13C13C!!13C13C!!2cy2cy1v41v32cy2cy1v41v32C12C11Uz1Uy2C12C11Uz1Uy1hO*071ky19f1ky0Uj1ky19f1ky0Uj1Sq1Sq0LD0OG1vH1vH0LD0OG1ky1ky0Uj0Uj16w16v0AD0AD0Uk0Uj10S10S1ky1ky0Gr0Gq0RA10S19f16v16w16v!!1AJ1mC0Gr0Gq1AJ1qb0Gr0Gq1Bu1Bu0Gr0Gq1qc1ni1hO1hO13C13C!!1Sg29l0Uj1kH1Sg29l0Uj1kH1AJ1mC0Gr0Gq1ky1t51b/1ky1b/1ky1b/1ky0u/",
    },
    {
        name: "Cambria",
        drawnIn: "Times New Roman",
        regular:
            "10u!*020wm0zT!!0wm0zT!!13x13x!!0wm0zT!!1zK1rY0C90C90wm0zT!!1Lu1Lu0C90C90I60WC!!1Lu1Lu0C90C91Lu1Lu0C90C91n+1ib1iO1iO1n+1ib1iO1iO1n+1ib1iO1iO0QK0QK!!0QK0QK!!1co1co!!1co1co!!20l20l1iY1iX20l20l1iY1iX2HB2HB24e24e2HC2HB24e24e1qT*071l016m1ib0ZA1l016m1ib0ZA1Xe1Xe0FQ0F31qT1qT0FQ0F31tX1tX0ZA0ZA1f81f70wm0wm0QP0QP0ZA0ZA1ib1ib0C90C90I60WC16m0ZA13x13x!!1zK1rY0C90C91zK1rY0C90C91Lu1Lu0C90C91n+1ib1iO1iO1co1co!!1+U2hK0ZA1gq1+U2hK0ZA1gq1zK1rY0C90C91l01tS1k/1tS1k/1tS1l01tS0wm",
        bold: "19g!*020Bf0DC!!0xU0AD!!16w16v!!0xU0AD!!1AJ1qb0Gr0Gq0xU0AE!!1Bu1Bu0Gr0Gq0RA10S!!1Bu1Bu0Gr0Gq1Bu1Bu0Gr0Gq1qc1ni1hO1hO1qc1ni1hO1hO1qc1ni1hO1hO0RA0Rz!!0RA0Rz!!13C13C!!13C13C!!2cy2cy1v41v32cy2cy1v41v32C12C11Uz1Uy2C12C11Uz1Uy1hO*071ky19f1ky0Uj1ky19f1ky0Uj1Sq1Sq0LD0OG1vH1vH0LD0OG1ky1ky0Uj0Uj16w16v0AD0AD0Uk0Uj10S10S1ky1ky0Gr0Gq0RA10S19f16v16w16v!!1AJ1mC0Gr0Gq1AJ1qb0Gr0Gq1Bu1Bu0Gr0Gq1qc1ni1hO1hO13C13C!!1Sg29l0Uj1kH1Sg29l0Uj1kH1AJ1mC0Gr0Gq1ky1t51b/1ky1b/1ky1b/1ky0u/",
    },
    {
        name: "Courier New",
        regular:
            "1tN!*021tN1tN!!1tN1tN!!1tN1tN!!1tN1tN!!1tN*021tO1tN1tN!!1tN*021tO1tN1tN!!1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN1tN!!1tN1tN!!1tN1tN!!1tN1tN!!1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN1tN!!1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN1tN!!1tN*021tO1tN*021tO1tN*021tO1tN*08",
        bold: "1tN!*021tN1tN!!1tN1tN!!1tN1tN!!1tN1tN!!1tN*021tO1tN1tN!!1tN*021tO1tN1tN!!1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN1tN!!1tN1tN!!1tN1tN!!1tN1tN!!1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN1tN!!1tN*021tO1tN*021tO1tN*021tO1tN*021tO1tN1tN!!1tN*021tO1tN*021tO1tN*021tO1tN*08",
    },
];
