<?xml version="1.0" encoding="UTF-8"?>
<!-- [MS-ODRAWXML] 5.21, http://schemas.microsoft.com/office/drawing/2014/chart/ac Schema: https://learn.microsoft.com/en-us/openspecs/office_standards/ms-odrawxml/5a2048a5-7116-48a9-95b6-9c7b8e70ff44 -->
<xsd:schema targetNamespace="http://schemas.microsoft.com/office/drawing/2014/chart/ac" elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns="http://schemas.microsoft.com/office/drawing/2014/chart/ac" xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:xsd="http://www.w3.org/2001/XMLSchema" blockDefault="#all">
   <xsd:import namespace="http://schemas.openxmlformats.org/drawingml/2006/chart" schemaLocation="../ISO-IEC29500-4_2016/dml-chart.xsd"/>
   <xsd:element name="multiLvlStrLit" type="c:CT_MultiLvlStrData"/>
 </xsd:schema>
