/**
 * Generates src/layout/equation-widths.ts: how wide each character of an equation of text is in Cambria Math, and the
 * italic correction Word adds after each italic letter, from Word's own PDFs of scripts/layout-probes/word-equations.ts and
 * word-equations2.ts, as word-equations2.py reads them. A character's width is how far Word put the next from it, past the
 * space it put between them, where Word drew both at places of their own, and otherwise its width in the PDF's Cambria
 * Math, to a thousandth of an em. Only the characters of an equation's text are kept: those of the fractions, roots and
 * sums of the probes are left out.
 *
 * Usage:
 *   python3 scripts/layout-probes/word-equations2.py --json scripts/layout-probes/word-equations.pdf \
 *     scripts/layout-probes/word-equations2.pdf > build/word-probes/word-equation-widths.json
 *   npm run run-ts -- scripts/generate-equation-widths.ts build/word-probes/word-equation-widths.json
 */
import { readFileSync, writeFileSync } from "node:fs";

const OUTPUT = "src/layout/equation-widths.ts";

// The characters of the fractions, roots and sums of the probes, which an equation's text doesn't have
const LEFT_OUT = new Set(["\u2211", "\u221a"]);

const [path] = process.argv.slice(2);
if (path === undefined) {
    console.error("Usage: npm run run-ts -- scripts/generate-equation-widths.ts <word-equations2.py's widths, as JSON>");
    process.exit(2);
}
const widths = JSON.parse(readFileSync(path, "utf8")) as Record<string, readonly [number, number]>;

/** A character as TypeScript writes it in a string: as it is when it is plain ASCII, and escaped otherwise */
const written = (character: string): string => {
    const code = character.codePointAt(0)!;
    if (code >= 0x20 && code < 0x7f && character !== '"' && character !== "\\") {
        return character;
    }
    return code > 0xffff ? `\\u{${code.toString(16)}}` : `\\u${code.toString(16).padStart(4, "0")}`;
};

const entries = Object.entries(widths)
    .filter(([character]) => !LEFT_OUT.has(character))
    .sort(([one], [other]) => one.codePointAt(0)! - other.codePointAt(0)!)
    .map(([character, [width, correction]]) => `    ["${written(character)}", [${width}, ${correction}]],`);

writeFileSync(
    OUTPUT,
    `/**
 * How wide each character of an equation of text is in Cambria Math, and the italic correction Word adds after each
 * italic letter, in thousandths of an em, as Word's PDFs of scripts/layout-probes/word-equations.ts and word-equations2.ts
 * show them.
 *
 * Generated by scripts/generate-equation-widths.ts. Do not edit by hand.
 *
 * @module
 */
export const EQUATION_WIDTHS: ReadonlyMap<string, readonly [number, number]> = new Map([
${entries.join("\n")}
]);
`,
);
console.log(`Wrote ${entries.length} characters to ${OUTPUT}`);
